### ISSUE TITLE
no sound when video quality change

### ISSUE THREAD

**Issue by DulalSandip** [Aboghazala/Hanash#4]
when i tried to change the video qyality and download,video is downloaded but it donot contains sound..will you fix this?

**Comment by Aboghazala** [comment]
@DulalSandip 

> when i tried to change the video qyality and download,video is downloaded but it donot contains sound..will you fix this?

youtube send 3 types of streams: 

1. Normal: normal video with audio embedded.
2. Video: video only with no audio
3. Audio: audio only with no video

you will find in "quality" drop down menu the video type in front of each stream, unfortunately youtube give maximum quality of normal video to 720p only and other higher quality streams i.e. 1080p are video without audio


I will add a feature to download these videos with audio merged since these videos without audio are useless

**Comment by Aboghazala** [comment]
@DulalSandip 
updated source code, now you can download any video with audio merged, however it requires 'ffmpeg' to be installed on your system
